# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        types: [file]  # override `types: [json]`
        files: \.(json|ipynb)$
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: fa505ab9c3e0fedafe1709fd7ac2b5f8996c670d # 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder-python-imports
    rev: 7885866bd38c852b5e042c4aeef0285d715ffeee # v3.16.0
    hooks:
    -   id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: c48217e1fc006c2dddd14df54e83b67da15de5cd # 7.3.0
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: c883505f64b59c3c5c9375191e4ad9f98e727ccd # v1.0.2
    hooks:
    - id: sphinx-lint
      types: [rst]
