[project]
name = "cusy-design-system"
version = "24.1.0"
description = "Richtlinien für Benutzeroberflächen, Code-Beispiele, Designtools und Ressourcen"
readme = "README.rst"
authors = [
  { name = "Veit Schiele", email = "veit@cusy.io" },
]
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = []
urls."Bug Tracker" = "https://github.com/cusyio/cusy-design-system/issues"
urls.Homepage = "https://github.com/cusyio/cusy-design-system"

[dependency-groups]
dev = [
  "cusy-design-system[docs]",
  "notebook",
  "pre-commit",
  "vale",
]
docs = [
  "altair",
  "bokeh",
  "furo",
  "geopandas",
  "ipyleaflet",
  "ipython",
  "leafmap",
  "maplibre",
  "nbsphinx",
  "sphinx-design",
  "sphinx-sitemap",
  "sphinxcontrib-svg2pdfconverter",
]

[tool.black]
line-length = 79

[tool.isort]
atomic = true
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
lines_after_imports = 2
lines_between_types = 1
not_skip = "__init__.py"
